insert into  maps (id, title, private) values ("5c1df62c-05df-4c74-baa3-2026a670c4e5",'De-engineered real-time groupware', false);
insert into  maps (title, private) values ('Phased contextually-based hierarchy', false);
insert into  maps (title, private) values ('Cloned optimal implementation', true);
insert into  maps (title, private) values ('Phased optimal benchmark', true);
insert into  maps (title, private) values ('Visionary zero defect concept', false);
insert into  maps (title, private) values ('Centralized secondary help-desk', true);
insert into  maps (title, private) values ('Up-sized empowering customer loyalty', false);
insert into  maps (title, private) values ('Grass-roots heuristic encoding', false);
insert into  maps (title, private) values ('Centralized asymmetric middleware', true);
insert into  maps (title, private) values ('Inverse empowering moratorium', false);
insert into  maps (title, private) values ('Phased human-resource task-force', false);
insert into  maps (title, private) values ('Innovative empowering budgetary management', false);
insert into  maps (title, private) values ('Self-enabling radical capacity', true);
insert into  maps (title, private) values ('Intuitive bottom-line capacity', false);
insert into  maps (title, private) values ('Enterprise-wide coherent focus group', true);
insert into  maps (title, private) values ('Sharable dedicated superstructure', true);
insert into  maps (title, private) values ('Optional eco-centric intranet', false);
insert into  maps (title, private) values ('Pre-emptive 3rd generation product', true);
insert into  maps (title, private) values ('Sharable zero administration challenge', false);
insert into  maps (title, private) values ('Compatible impactful toolset', false);
insert into  maps (title, private) values ('Fully-configurable grid-enabled groupware', false);
insert into  maps (title, private) values ('Ameliorated dynamic throughput', false);
insert into  maps (title, private) values ('Diverse non-volatile product', false);
insert into  maps (title, private) values ('Reduced explicit benchmark', false);
insert into  maps (title, private) values ('Managed context-sensitive collaboration', true);
insert into  maps (title, private) values ('Object-based grid-enabled projection', false);
insert into  maps (title, private) values ('Adaptive heuristic algorithm', true);
insert into  maps (title, private) values ('Sharable attitude-oriented standardization', false);
insert into  maps (title, private) values ('Secured bifurcated benchmark', true);
insert into  maps (title, private) values ('Upgradable cohesive process improvement', false);
insert into  maps (title, private) values ('Multi-tiered client-driven firmware', true);
insert into  maps (title, private) values ('Proactive tangible secured line', false);
insert into  maps (title, private) values ('Triple-buffered 5th generation collaboration', false);
insert into  maps (title, private) values ('Open-architected high-level framework', false);
insert into  maps (title, private) values ('Ameliorated radical throughput', true);
insert into  maps (title, private) values ('Enterprise-wide object-oriented open architecture', true);
insert into  maps (title, private) values ('Reverse-engineered attitude-oriented help-desk', true);
insert into  maps (title, private) values ('Business-focused asynchronous groupware', false);
insert into  maps (title, private) values ('Profound responsive internet solution', false);
insert into  maps (title, private) values ('Focused systemic collaboration', true);
insert into  maps (title, private) values ('Customer-focused cohesive focus group', true);
insert into  maps (title, private) values ('Multi-layered dynamic paradigm', false);
insert into  maps (title, private) values ('Expanded asynchronous task-force', false);
insert into  maps (title, private) values ('Re-contextualized eco-centric intranet', true);
insert into  maps (title, private) values ('Multi-lateral client-server local area network', false);
insert into  maps (title, private) values ('Versatile 3rd generation flexibility', true);
insert into  maps (title, private) values ('Adaptive zero tolerance product', false);
insert into  maps (title, private) values ('Adaptive solution-oriented knowledge user', true);
insert into  maps (title, private) values ('Polarised background algorithm', true);
insert into  maps (title, private) values ('Programmable dynamic matrix', false);
insert into  maps (title, private) values ('Future-proofed explicit adapter', false);
insert into  maps (title, private) values ('Fully-configurable exuding archive', false);
insert into  maps (title, private) values ('Down-sized object-oriented synergy', true);
insert into  maps (title, private) values ('Automated context-sensitive orchestration', false);
insert into  maps (title, private) values ('Phased context-sensitive budgetary management', true);
insert into  maps (title, private) values ('User-centric regional pricing structure', false);
insert into  maps (title, private) values ('Assimilated demand-driven intranet', false);
insert into  maps (title, private) values ('Grass-roots neutral strategy', false);
insert into  maps (title, private) values ('Decentralized impactful analyzer', true);
insert into  maps (title, private) values ('Right-sized global groupware', true);
insert into  maps (title, private) values ('Innovative multi-tasking complexity', false);
insert into  maps (title, private) values ('User-friendly well-modulated strategy', true);
insert into  maps (title, private) values ('Robust mission-critical process improvement', true);
insert into  maps (title, private) values ('Persevering bifurcated application', false);
insert into  maps (title, private) values ('Realigned composite structure', true);
insert into  maps (title, private) values ('Horizontal needs-based installation', false);
insert into  maps (title, private) values ('Up-sized local internet solution', true);
insert into  maps (title, private) values ('Realigned optimal Graphic Interface', false);
insert into  maps (title, private) values ('Reduced full-range projection', false);
insert into  maps (title, private) values ('Open-architected radical synergy', false);
insert into  maps (title, private) values ('Ameliorated maximized framework', true);
insert into  maps (title, private) values ('Programmable local strategy', false);
insert into  maps (title, private) values ('Advanced motivating conglomeration', true);
insert into  maps (title, private) values ('Multi-tiered transitional algorithm', true);
insert into  maps (title, private) values ('Secured web-enabled solution', false);
insert into  maps (title, private) values ('Public-key multimedia contingency', true);
insert into  maps (title, private) values ('Digitized local structure', false);
insert into  maps (title, private) values ('Adaptive tertiary budgetary management', false);
insert into  maps (title, private) values ('Configurable non-volatile collaboration', false);
insert into  maps (title, private) values ('Diverse human-resource emulation', true);
insert into  maps (title, private) values ('Inverse asymmetric focus group', true);
insert into  maps (title, private) values ('Open-architected background utilisation', false);
insert into  maps (title, private) values ('Grass-roots client-driven adapter', false);
insert into  maps (title, private) values ('Profit-focused foreground data-warehouse', true);
insert into  maps (title, private) values ('User-friendly empowering matrix', true);
insert into  maps (title, private) values ('Networked user-facing ability', true);
insert into  maps (title, private) values ('Cloned stable moratorium', false);
insert into  maps (title, private) values ('Integrated 24/7 Graphical User Interface', false);
insert into  maps (title, private) values ('Ameliorated interactive superstructure', true);
insert into  maps (title, private) values ('Secured zero tolerance system engine', true);
insert into  maps (title, private) values ('Robust coherent local area network', true);
insert into  maps (title, private) values ('Decentralized attitude-oriented utilisation', true);
insert into  maps (title, private) values ('Quality-focused attitude-oriented time-frame', false);
insert into  maps (title, private) values ('Managed client-driven flexibility', false);
insert into  maps (title, private) values ('Networked stable data-warehouse', false);
insert into  maps (title, private) values ('Up-sized zero tolerance access', true);
insert into  maps (title, private) values ('Synergized impactful neural-net', true);
insert into  maps (title, private) values ('Ergonomic executive policy', true);
insert into  maps (title, private) values ('Diverse background archive', false);
insert into  maps (title, private) values ('Open-architected multi-tasking system engine', false);

